import pyomo.environ as pyo
import pandas as pd

from zld_params import (
    add_sets,
    add_time_set,
    add_time_series_params,
    add_thermo_params,
    add_process_params,
    add_economic_params,
    add_zld_params
)

Schedule_effic = pd.read_csv("sched_eff.csv", usecols=["Efficiency"]).to_numpy().flatten()
Schedule_elec  = pd.read_csv("DIABLOCN_2_N001_PRICES.csv", usecols=["LMP"]).to_numpy().flatten()




model = pyo.ConcreteModel()



add_sets(model)
add_time_set(model, 8760)
add_time_series_params(model, sched_price_elec=Schedule_elec, sched_cyc_eff=Schedule_effic)
add_thermo_params(model, oversize_factor=1.0)
add_process_params(model, process_scale={})
add_economic_params(model, price_scale={}, cost_scale={})
add_zld_params(model, yield_scale=1.0)



# variables 

model.m_hot_tes               = pyo.Var(model.T, domain=pyo.NonNegativeReals)                               # units: kg,            inventory in high-temp hot storage 
model.m_dot_hot_tes           = pyo.Var(model.T, domain=pyo.NonNegativeReals)                               # units: kg/s,          mass flow out of high-temp hot storage
model.m_dot_hpt               = pyo.Var(model.T, domain=pyo.NonNegativeReals)                               # units: kg/s,          mass flow at the high pressure turbine inlet 
model.m_dot_extract           = pyo.Var(model.T, domain=pyo.NonNegativeReals)                               # units: kg/s,          mass flow of steam extracted from power cycle
model.m_cold_tes              = pyo.Var(model.T, domain=pyo.NonNegativeReals)                               # units: kg,            inventory in low-temp hot storage
model.m_dot_cold_tes          = pyo.Var(model.T, model.processes, domain=pyo.NonNegativeReals)              # units: kg/s,          mass flow out of low-temperature storage to med
model.w_dot_gen               = pyo.Var(model.T, domain=pyo.NonNegativeReals)                               # units: kW_e,          electricity produced by power cycle
model.m_hot_tes_max           = pyo.Var(domain=pyo.NonNegativeReals)                                        # units: kWh_th,        high-temp thermal storage maximum inventory
model.m_cold_tes_max          = pyo.Var(domain=pyo.NonNegativeReals)                                        # units: kWh_th,        low-temp thermal storage maximum inventory
model.m_dot_hpt_Delta_up      = pyo.Var(model.T, domain=pyo.NonNegativeReals)                               # units: kg/s,          upward change in hpt mass flow from one time step to the next 
model.m_dot_hpt_Delta_dn      = pyo.Var(model.T, domain=pyo.NonNegativeReals)                               # units: kg/s,          downward change in hpt mass flow from one time step to the next
model.y_link_active           = pyo.Var(model.links, within=pyo.Binary)                                     # units: --,            1 if there is flow from process q to process p; 0 otherwise
model.y_process_active        = pyo.Var(model.processes, within=pyo.Binary)                                 # units: --,            1 if process p is active; 0 otherwise
model.v_dot_in                = pyo.Var(model.T, model.processes, within=pyo.NonNegativeReals)              # units: m^3/hr,        volumetric flow rate entering each process
model.v_dot_conc              = pyo.Var(model.T, model.processes, within=pyo.NonNegativeReals)              # units: m^3/hr,        volumetric flow rate of concentrated stream leaving each process
model.v_dot_dil               = pyo.Var(model.T, model.processes, within=pyo.NonNegativeReals)              # units: m^3/hr,        volumetric flow rate of diluted stream leaving each process
model.v_dot_link              = pyo.Var(model.T, model.links, within=pyo.NonNegativeReals)                  # units: m^3/hr,        volumetric flow rate from an upstream process to a downstream process
model.elec_used               = pyo.Var(model.T, model.processes, within=pyo.NonNegativeReals)              # units: kW_e,          electricity used by each process
model.elec_sold               = pyo.Var(model.T, within=pyo.NonNegativeReals)                               # units: kW_e,          electricity sold to the grid from each power cycle configuration   
model.q_generated             = pyo.Var(model.T, within=pyo.NonNegativeReals)                               # units: kWh_th,        heat generated by each power cycle from steam extractions
model.q_used                  = pyo.Var(model.T, model.processes, within=pyo.NonNegativeReals)              # units: kWh_th,        heat used by each process
model.f_ion_in                = pyo.Var(model.T, model.processes, model.ions, within=pyo.NonNegativeReals)  # units: kg/h,          flow of each ion into each process
model.f_ion_conc              = pyo.Var(model.T, model.processes, model.ions, within=pyo.NonNegativeReals)  # units: kg/h,          ion flow in concentrated stream leaving process p
model.f_ion_dil               = pyo.Var(model.T, model.processes, model.ions, within=pyo.NonNegativeReals)  # units: kg/h,          ion flow in diluted stream leaving process p
model.f_ion_link              = pyo.Var(model.T, model.links, model.ions, within=pyo.NonNegativeReals)      # units: kg/h,          ion flow between two processes
model.li_recovered_ed         = pyo.Var(model.T, within=pyo.NonNegativeReals)                               # units: kg/h,          total Li recovered
model.v_dot_cap               = pyo.Var(model.processes, within=pyo.NonNegativeReals)                       # units: m^3/day,       capacity of each process


# power cycle constraints

# fixed: convert steam to power in the power cycle
def steam_to_power(model, t):
    return model.w_dot_gen[t] == (
        model.Eff_cycle[t]*model.W_dot_ref*
        (model.Slope_power_curve*model.m_dot_hpt[t]/model.M_dot_hx1_steam_nom
            - model.F_lpt_post*model.m_dot_extract[t]/model.M_dot_hx1_steam_nom
            - model.Interc_power_curve))
model.steam_to_power = pyo.Constraint(model.T, rule=steam_to_power)



# fixed: limits extraction from power cycle
def steam_extraction_limit(model, t):
    return model.m_dot_extract[t] <= model.F_ext * model.m_dot_hpt[t]
model.steam_extraction_limit = pyo.Constraint(model.T, rule=steam_extraction_limit)



# fixed: limits flow to hpt depending on turbine size
def bound_hpt_flow(model, t):
    return model.m_dot_hpt[t] <= model.M_dot_hpt_max
model.bound_hpt_flow = pyo.Constraint(model.T, rule=bound_hpt_flow)



# fixed: relates salt mass flow out of hot storage to steam flow in power cycle
def hx1_conversion(model,t):
    return model.m_dot_hpt[t] == model.K_hx1 * model.m_dot_hot_tes[t]
model.hx1_conversion = pyo.Constraint(model.T, rule=hx1_conversion)



# fixed: limits hot tes inventory
def hot_tes_limit(model,t):
    return model.m_hot_tes[t] <= model.m_hot_tes_max
model.hot_tes_limit = pyo.Constraint(model.T, rule=hot_tes_limit)



# fixed: tracks power ramping upwards 
def hpt_track_up(model, t):
    return model.m_dot_hpt_Delta_up[t] >= model.m_dot_hpt[t] - model.m_dot_hpt[t-1]
model.hpt_track_up = pyo.Constraint(model.T-[1], rule=hpt_track_up)



# fixed: tracks power ramping downwards
def hpt_track_down(model, t):
    return model.m_dot_hpt_Delta_dn[t] >= model.m_dot_hpt[t-1] - model.m_dot_hpt[t]
model.hpt_track_down = pyo.Constraint(model.T-[1], rule=hpt_track_down)



# fixed: limits power ramping upwards based on power ramp limit
def hpt_ramp_up(model,t):
    return model.m_dot_hpt_Delta_up[t] <= model.W_dot_ramp_max/model.K_power*model.Delta_t
model.hpt_ramp_up = pyo.Constraint(model.T-[1], rule=hpt_ramp_up)



# fixed: limits power ramping downwards based on power ramp limit
def hpt_ramp_down(model,t):
    return model.m_dot_hpt_Delta_dn[t] <= model.W_dot_ramp_max/model.K_power*model.Delta_t
model.hpt_ramp_down = pyo.Constraint(model.T-[1], rule=hpt_ramp_down)  



# fixed: conserves mass in hot tes
def hot_tes_inventory(model, t):  
    if t > 1:
        return model.m_hot_tes[t] == (model.M_dot_salt[t] - model.m_dot_hot_tes[t]) * model.Convert_time * model.Delta_t + model.m_hot_tes[t-1]
    else:
        return model.m_hot_tes[t] == (model.M_dot_salt[t] - model.m_dot_hot_tes[t]) * model.Convert_time * model.Delta_t 
model.hot_tes_inventory = pyo.Constraint(model.T, rule=hot_tes_inventory)



# fixed: conserves mass in cold tes low-temp tes inventory tracking between time steps
def cold_tes_inventory(model, t):
    if t > 1:
        return model.m_cold_tes[t] == model.m_cold_tes[t-1] + (
            model.K_hx2 * model.m_dot_extract[t] 
            - sum(model.m_dot_cold_tes[t, p] for p in ['MED', 'CRY'])) * model.Delta_t
    else:
        return model.m_cold_tes[t] == (
            model.K_hx2 * model.m_dot_extract[t] 
            - sum(model.m_dot_cold_tes[t, p] for p in ['MED', 'CRY'])) * model.Delta_t
model.cold_tes_inventory = pyo.Constraint(model.T, rule=cold_tes_inventory)



# fixed: relates electricity used by each process to per unit requirements
def electric_used_by_process(model, t, p):
    return model.elec_used[t,p] == model.Elec_required[p] * model.v_dot_in[t,p]
model.electric_used_by_process = pyo.Constraint(model.T, model.processes, rule=electric_used_by_process)



# fixed: balances electricity 
def electric_balance(model, t):
    return model.elec_sold[t] == model.w_dot_gen[t] - sum(model.elec_used[t, p] for p in model.processes)
model.electric_balance = pyo.Constraint(model.T, rule=electric_balance)



# fixed: routes cold storage to med or cry
def cold_tes_balance(model, t, p):
    return model.m_dot_cold_tes[t, p] * model.Delta_H_hx2_water * model.Delta_t == model.q_used[t, p]
model.cold_tes_balance = pyo.Constraint(model.T, model.processes, rule=cold_tes_balance)



# fixed: relates heat used by each process to per unit requirements
def heat_used_by_process(model, t, p):
    return model.q_used[t, p] == model.Q_required[p] * model.v_dot_in[t, p]
model.heat_used_by_process = pyo.Constraint(model.T, model.processes, rule=heat_used_by_process)



# fixed: conserves ions through system
def ion_conservation(m, t, p, i):
    return m.f_ion_in[t,p,i] == m.f_ion_conc[t,p,i] + m.f_ion_dil[t,p,i]
model.ion_conservation = pyo.Constraint(model.T, model.processes, model.ions, rule=ion_conservation)



# fixed: relates ions into a process as sum of ions on upstream links
def ion_mass_in(m,t,p,i):
    return m.f_ion_in[t,p,i] == sum(m.f_ion_link[t,(q,p),i]for (q,r) in m.links if r == p)
model.ion_mass_in = pyo.Constraint(model.T, model.processes, model.ions, rule=ion_mass_in)


# fixed: relates ion flow on link between seawater and process to seawater concentration
def sw_ion_link(m,t,p,i):
    if ('SW',p) not in m.links:
        return pyo.Constraint.Skip
    return m.f_ion_link[t,('SW',p),i] == m.v_dot_link[t,('SW',p)] * m.Conc_sw[i]
model.sw_ion_link = pyo.Constraint(model.T, model.processes, model.ions, rule=sw_ion_link)



# fixed: constrains flow only on active links
def link_gate_all(m, t, p, q):
    return m.v_dot_link[t,(p,q)] <= m.V_dot_max * m.y_link_active[(p,q)]
model.link_gate_all = pyo.Constraint(model.T, model.links, rule=link_gate_all)



# fixed: routes concentrated stream to next node
def conc_outflow_balance(m, t, p):
    if p == 'SW':
        return pyo.Constraint.Skip

    outs = [q for (p2,q) in m.links if p2 == p]
    if not outs:
        return pyo.Constraint.Skip

    return sum(m.v_dot_link[t, (p,q)] for q in outs) == m.v_dot_conc[t, p]

model.conc_outflow_balance = pyo.Constraint(model.T, model.processes, rule=conc_outflow_balance)



# fixed: constrains flow to one downstream process
def one_outgoing(m, t, p):
    if p == 'SW':
        return pyo.Constraint.Skip

    outs = [q for (p2, q) in m.links if p2 == p]
    if not outs:
        return pyo.Constraint.Skip

    return sum(m.y_link_active[(p, q)] for q in outs) <= 1

model.one_outgoing = pyo.Constraint(model.T, model.processes, rule=one_outgoing)


# fixed: routes ion flow in concentrated stream though downstream links
def route_conc_ions(m, t, p, i):
    if p in ['SW', 'CRY']:
        return pyo.Constraint.Skip

    outs = [q for (p2, q) in m.links if p2 == p]
    if not outs:
        return pyo.Constraint.Skip

    return sum(m.f_ion_link[t, (p,q), i] for q in outs) == m.f_ion_conc[t, p, i]

model.route_conc_ions = pyo.Constraint(model.T, model.processes, model.ions, rule=route_conc_ions)



# fixed: conserves volumetric flow through each process
def process_flow_balance(model, t, p):
    return model.v_dot_in[t, p] == model.v_dot_conc[t, p] + model.v_dot_dil[t, p]
model.process_flow_balance = pyo.Constraint(model.T, model.processes, rule=process_flow_balance)



# fixed: forces flow on active links
# I'm not sure if this constraint is necessary
def no_flow_inactive(model, t, q, p):
    return model.v_dot_link[t, (q,p)] >= model.V_dot_min * model.y_link_active[q, p]
model.no_flow_inactive = pyo.Constraint(model.T, model.links, rule=no_flow_inactive)



# fixed: limits inflow to each process
def inlet_flow_max(model, t, p):
    return model.v_dot_in[t, p] <= model.V_dot_max * model.y_process_active[p]
model.inlet_flow_max = pyo.Constraint(model.T, model.processes, rule=inlet_flow_max)



# fixed: forces flow if process is active
def inlet_flow_min(model, t, p):
    return model.v_dot_in[t, p] >= model.V_dot_min * model.y_process_active[p]
model.inlet_flow_min = pyo.Constraint(model.T, model.processes, rule=inlet_flow_min)
   


# fixed: limits seawater feed to one process 
def single_sw_feed(model):
    return sum(model.y_link_active['SW', p] for p in model.processes if ('SW', p) in model.links) <= 1
model.single_sw_feed = pyo.Constraint(rule=single_sw_feed)



# fixed: limits downstream process to one upstream process
def single_upstream(m, q):
    return sum(m.y_link_active[(p2,q)] for (p2,q2) in m.links if q2==q) <= 1
model.single_upstream = pyo.Constraint(model.processes, rule=single_upstream)



# fixed: check for downstream link and sends outlet flow to one downstream process
def single_downstream(m, p):
    terms = [m.y_link_active[(p,q)] for (p2,q) in m.links if p2 == p]
    if not terms:
        return pyo.Constraint.Skip
    return sum(terms) <= 1
model.single_downstream = pyo.Constraint(model.processes, rule=single_downstream)



# fixed: enforces link between processes can only be activated if the upstream process is activated
def upstream_activation(model, q, p):
    if q == 'SW':
        return pyo.Constraint.Skip
    return model.y_link_active[(q,p)] <= model.y_process_active[q]
model.upstream_activation = pyo.Constraint(model.links, rule=upstream_activation)



# fixed: enforces link between processes can only be activated if the downstream process is activated
def downstream_activation(model, q, p):
    return model.y_link_active[q,p] <= model.y_process_active[p]
model.downstream_activation = pyo.Constraint(model.links, rule=downstream_activation)



# fixed: relates inflow to process as sum of upstream links
def inlet_flow(m, t, p):
    inflow = sum(m.v_dot_link[t, (p2,p)] for (p2,q) in m.links if q==p)
    return m.v_dot_in[t, p] == inflow
model.inlet_flow = pyo.Constraint(model.T, model.processes, rule=inlet_flow)



# fixed: limits seawater intake to maximum
def seawater_intake(m, t):
    return sum(m.v_dot_link[t, ('SW',q)] for (p2,q) in m.links if p2=='SW') <= m.V_dot_max
model.seawater_intake = pyo.Constraint(model.T, rule=seawater_intake)



# fixed: sets ro recovery ratio relationship 
def recovery_ro(model, t):
    return model.v_dot_dil[t, 'RO'] == model.Recovery_ro * model.v_dot_in[t, 'RO']
model.recovery_ro = pyo.Constraint(model.T, rule=recovery_ro)



# fixed: enforces no ions in diluted ro stream
def ro_diluted(model, t, p, i):
    if p!= 'RO':
        return pyo.Constraint.Skip
    return model.f_ion_dil[t, 'RO', i] == 0.0
model.ro_diluted = pyo.Constraint(model.T, model.processes, model.ions, rule=ro_diluted)



# fixed: enforces correct recovery ratio for med 
def recovery_med(model, t):
    return model.v_dot_dil[t, 'MED'] == (
        model.v_dot_in[t, 'MED'] * model.Recovery_sw_to_med * (1 - model.y_link_active['RO','MED']) + 
        model.v_dot_in[t, 'MED'] * model.Recovery_ro_to_med * model.y_link_active['RO','MED'])
model.recovery_med = pyo.Constraint(model.T, rule=recovery_med)



# fixed: enforces no ions in diluted med stream
def med_diluted(model, t, p, i):
    if p!= 'MED':
        return pyo.Constraint.Skip
    return model.f_ion_dil[t, 'MED', i] == 0.0
model.med_diluted = pyo.Constraint(model.T, model.processes, model.ions, rule=med_diluted)



# fixed: enforces no concentrated flow from cry
def cry_no_concentrate(model, t):
    return model.v_dot_conc[t, 'CRY'] == 0.0
model.cry_no_concentrate = pyo.Constraint(model.T, rule=cry_no_concentrate)

    

# fixed: enforces no ions in diluted cry stream 
def cry_diluted(model, t, i):
    return model.f_ion_dil[t, 'CRY', i] == 0.0
model.cry_diluted = pyo.Constraint(model.T, model.ions, rule=cry_diluted)


# fixed: enforces ratio between na and li in ed stream
def ed_precip_ratio(model,t):
    return model.f_ion_dil[t,'ED','Na'] == model.Ratio_na_to_li * model.f_ion_dil[t,'ED','Li']
model.ed_precip_ratio = pyo.Constraint(model.T, rule=ed_precip_ratio)



# fixed: relates li recovered to yield 
def li_recovery(model,t):
    return model.li_recovered_ed[t] == model.yield_ed_li * model.f_ion_in[t,'ED','Li']
model.li_recovery = pyo.Constraint(model.T, rule=li_recovery)



# fixed: equates li recovered with amount in diluted stream
def li_mass_balance(model, t):
    return model.li_recovered_ed[t] == model.f_ion_dil[t,'ED','Li']
model.li_mass_balance = pyo.Constraint(model.T, rule=li_mass_balance)



# fixed: splits na between ed outlet streams
def ed_split(model, t):
    return (model.f_ion_conc[t,'ED','Na'] * model.v_dot_dil[t,'ED']
        == model.f_ion_dil[t,'ED','Na'] * model.v_dot_conc[t, 'ED'])
model.ed_split = pyo.Constraint(model.T, rule=ed_split)



# fixed: sets capacity on processes
def capacity_limit_rule(m, t, p):
    return m.v_dot_in[t,p] <= m.v_dot_cap[p]/24
model.capacity_limit = pyo.Constraint(model.T, model.processes, rule=capacity_limit_rule)



# objective function 
profit = sum(
    model.Price_li * model.li_recovered_ed[t]
    + model.Price_water * (model.v_dot_dil[t, 'RO']+model.v_dot_dil[t, 'MED']+model.v_dot_dil[t, 'CRY'])
    + model.Price_elec[t] * model.elec_sold[t]
    for t in model.T)

capex = sum(model.K_process[p] * model.v_dot_cap[p] for p in model.processes)

model.obj = pyo.Objective(expr=profit-capex, sense=pyo.maximize)


model.pprint()


